apiVersion: v1
kind: Service
metadata:
  name: lists
  labels:
    app: lists
spec:
  selector:
    app: lists
  ports:
  - port: 80
    protocol: TCP
    name: http
  - port: 443
    protocol: TCP
    name: https
  type: LoadBalancer
