version: '3.5'
services:
  web:
    image: node:alpine
    working_dir: /usr/local/src
    command: yarn run dev
    ports:
      - 8080:8080
    volumes:
      - .:/usr/local/src
      - node_modules:/usr/local/src/node_modules
volumes:
  node_modules: {}
