version: '3.5'
services:
  web:
    build: .
    ports:
      - 8000:8000
      - 5858:5858
    volumes:
      - .:/usr/local/src
      - node_modules:/usr/local/src/node_modules
    depends_on:
      - lists-db
  lists-db:
    image: redis
volumes:
  node_modules: {}
